spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

kakao:
  rest:
    REST_API_KEY: ${KAKAO_REST_API_KEY}
  javascript:
    JavaScript_KEY: ${KAKAO_JAVASCRIPT_KEY}
  url:
    address: https://dapi.kakao.com/v2/local/geo/coord2address.json
    region: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  send-default-pii: true
  logging:
    enabled: true
    minimum-event-level: warn
    # 에러 전 상황 파악을 위해 info 레벨 로그를 추적
    minimum-breadcrumb-level: info
  environment: ${spring.profiles.active}
